version: '2.2'

services:
  php_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8089:80"
      # volumes:
      # - ./docker/config/php.ini:/usr/local/etc/php/php.ini
      # - ./:/var/www/html/:z
    depends_on:
      rabbitmq:
        condition: service_healthy

  node_app:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  python_app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 1
    # volumes:
    #   - rabbitmq-data:/var/lib/rabbitmq
# volumes:
#   rabbitmq-data: